---

name: Python

"on":
  pull_request:
    branches:
      - develop
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Lint with flake8
        run: |
          command -v flake8 1>/dev/null || pip install flake8
          make flake8

      - name: Lint with black
        run: |
          command -v black 1>/dev/null || pip install black
          make blackcheck

      - name: Type-check with mypy
        run: |
          sudo apt update
          sudo env DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends python3-virtualenv
          make mypy

      - name: Test with pytest
        env:
          CORE_GRPC_NODE: ${{ secrets.CORE_GRPC_NODE }}
          DATA_GRPC_NODE: ${{ secrets.DATA_GRPC_NODE }}
          WALLETSERVER: ${{ secrets.WALLETSERVER }}
        run: |
          command -v pipenv 1>/dev/null || pip install pipenv
          make test

      - name: Check archive file counts
        run: |
          python3 setup.py sdist bdist_wheel
          make check_dist
