---

name: YAML

"on":
  pull_request:
    branches:
      - develop
      - main
      - master
    paths-ignore:
      - "grpc/clients/**"
  push:
    branches:
      - develop
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-pre[0-9]+"

jobs:

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |
            extends: default
            rules:
              line-length:
                max: 160
